# **Notebook em linguagem R**

Conceitos básicos em linguagem R para a disciplina de Estatística.

In [ ]:
# Coletar Dados
venda <- 1.59
lucro <- 40

# Processar dados
lucro_per <- lucro/100

custo <- round(
    venda / (1 + lucro_per),
    2
)

# imprimir resultado
print(paste('O preço de custo é: R$', custo))

[1] "O preço de custo é: R$ 1.14"

## **Vetores**

Os vetores em R são equivalentes ao conceito de lista em Python.

In [ ]:
# Coletar valor das notas
n1 <- 6.5
n2 <- 4.2
n3 <- 8.9

# Armazenar as três notas em um conjunto (vetor)
notas <- c(n1, n2, n3)

# Calcular a média das notas a partir do vetor
media <- round(
  mean(notas),
  1)

# Contar quantas notas há no vetor
qtde_notas <- length(notas)
print(paste("Quantidade de notas:", qtde_notas))

# Apresentar o resultado
print(paste("Média:", media))

[1] "Quantidade de notas: 3"
[1] "Média: 6.5"

## **DataFrames**

In [ ]:
dados <- data.frame(
  nome = c('Aluno 1', 'Aluno 2', 'Aluno 3'),
  media = c(4.5, 6.8, 9.9),
  frequencia = c(70, 80, 90)
)

dados

  nome    media frequencia
1 Aluno 1 4.5   70
2 Aluno 2 6.8   80
3 Aluno 3 9.9   90

In [ ]:
dados$aprovado <- dados$media >= 6

dados

  nome    media frequencia aprovado
1 Aluno 1 4.5   70         FALSE
2 Aluno 2 6.8   80          TRUE
3 Aluno 3 9.9   90          TRUE

## **Carregar arquivo externo**

Primeiramente é necessário fazer o upload do arquivo no ambiente colab e, na sequência, "chamar" o arquivo para dentro no notebook.

In [ ]:
# Instalar o pacote "readxl"
install.packages("readxl")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
# Carregar o pacote
library(readxl)

In [ ]:
# Abrir arquivo Excel

df <- read_excel("Dados_CalourosBCD.xlsx")
df

   ID Semestre Cidade de origem  Estado de origem
1   1 2026/1   Blumenau          SC
2   2 2026/1   Blumenau          Santa Catarina
3   3 2026/1   Belo Horizonte    Minas Gerais
4   4 2026/1   Blumenau          Santa Catarina
5   5 2026/1   Blumenau          Santa Catarina
6   6 2026/1   Blumenau          Santa Catarina
7   7 2026/1   Joinville         Santa Catarina
8   8 2026/1   Blumenau          SC
9   9 2026/1   Timbó             Santa Catarina
10 10 2026/1   Timbó             Santa Catarina
11 11 2026/1   blumenau          sc
12 12 2026/1   Blumenau          Santa Catarina
13 13 2026/1   Gaspar            SC
14 14 2026/1   Gaspar            Santa Catarina
15 15 2026/1   Curitibanos       Santa Catarina
16 16 2026/1   Timbó             SC
17 17 2026/1   Blumenau          SC
18 18 2026/1   Belo Horizonte    Minas Gerais
19 19 2026/1   São Gonçalo       Rio de Janeiro
20 20 2026/1   Londres           Estrangeiro
21 21 2026/1   Otacílio Costa    Sc
22 22 2026/1   Blumenau          SC
23 23 2026/1   Blumenau          Santa catarina
24 24 2026/1   Blumenau          SC
25 25 2026/1   Blumenau          Santa Catarina
26 26 2026/1   Teresópolis       RJ
27 27 2026/1   Chapecó           Santa Catarina
28 28 2026/1   Blumenau          Santa Catarina
29 29 2026/1   blumenau          SC
30 30 2026/1   Blumenau          Santa Catarina
31 31 2026/1   Blumenau          Santa Cararina
32 32 2026/1   Caraguatatuba     São Paulo
33 33 2026/1   Blumenau          SC
34 34 2026/1   BLUMENAU          SC
35 35 2026/1   Rodeio            Santa Catarina
36 36 2026/1   Ilhota            Santa Catarina
37 37 2026/1   Blumenau          Santa Catarina
38 38 2026/1   Santa Maria       RS
39 39 2026/1   São Paulo         SP
40 40 2026/1   Gaspar            Santa Catarina
41 41 2026/1   Indaial           Sc
42 42 2026/1   Ilhota            Sc
43 43 2026/1   Blumenau          SC
44 44 2026/1   Recife            Pernambuco
45 45 2026/1   Belém             Para
46 46 2026/1   Foz do Iguaçu     Paraná
47 47 2026/1   Blumenau          SC
48 48 2026/1   Pomerode          Santa Catarina
49 49 2026/1   Blumenau          SC
50 50 2026/1   Recife            Pernambuco
51 51 2026/1   Juazeiro do Norte CE
52 52 2026/1   Jaragua do Sul    Sc
53 53 2026/1   Blumenau          SC
54 54 2026/1   Lages             Santa Catarina
55 55 2026/1   São Bento do Sul  Santa Catarina
56 56 2026/1   Recife            Pernambuco
   Cidade em que você reside atualmente.
1  Blumenau
2  Blumenau
3  Blumenau
4  Blumenau
5  Blumenau
6  Blumenau
7  Blumenau
8  Blumenau
9  Timbó
10 Rodeio
11 blumenau
12 Blumenau
13 Gaspar
14 Gaspar
15 Blumenau
16 Timbó
17 Blumenau
18 Blumenau
19 Blumenau
20 Blumenau
21 Blumenau
22 Blumenau
23 blumenau
24 Blumenau
25 Blumenau
26 Blumenau
27 Blumenau
28 Blumenau
29 blumenau
30 Blumenau
31 Blumenau
32 Blumenau
33 Blumenau
34 BLUMENAU
35 Rodeio
36 Ilhota
37 Blumenau
38 Blumenau
39 Timbó
40 Gaspar
41 Rodeio
42 Ilhota
43 Blumenau
44 Blumenau
45 Blumenau
46 Blumenau
47 Blumenau
48 Pomerode
49 Blumenau
50 Blumenau
51 Pomerode
52 Blumenau
53 Blumenau
54 Blumenau
55 Gaspar
56 Blumenau
   Você já morou em quantas cidades diferentes?
1  1
2  0
3  3
4  0
5  1
6  3
7  2
8  1
9  0
10 1
11 1
12 1
13 1
14 0
15 2
16 0
17 1
18 3
19 3
20 2
21 3
22 0
23 2
24 2
25 1
26 2
27 3
28 1
29 1
30 0
31 1
32 3
33 1
34 1
35 1
36 6
37 5
38 3
39 2
40 1
41 0
42 1
43 1
44 2
45 2
46 1
47 1
48 0
49 1
50 2
51 2
52 6
53 3
54 9
55 2
56 2
   Você já teve contato com programação?
1  Avançado
2  Intermediário
3  Básico
4  Básico
5  Básico
6  Básico
7  Básico
8  Básico
9  Básico
10 Básico
11 Nunca
12 Nunca
13 Básico
14 Básico
15 Nunca
16 Básico
17 Intermediário
18 Nunca
19 Básico
20 Básico
21 Básico
22 Intermediário
23 Básico
24 Básico
25 Nunca
26 Intermediário
27 Básico
28 Nunca
29 Nunca
30 Básico
31 Avançado
32 Intermediário
33 Nunca
34 Nunca
35 Intermediário
36 Nunca
37 Nunca
38 Básico
39 Intermediário
40 Básico
41 Básico
42 Intermediário
43 Intermediário
44 Básico
45 Básico
46 Intermediário
47 Intermediário
48 Nunca
49 Intermediário
50 Intermediário
51 Básico
52 Básico
53 Básico
54 Básico
55 Intermediário
56 Intermediário
   Qual linguagem você já utilizou?
1  SQL, Python, R
2  Java
3  C#
4  Java script
5  Java, SQL, CSS, Javascript
6  Python
7  C#
8  Java, Javascript
9  Python, SQL
10 Java, Python, JavaScript, SQL
11 NA
12 NA
13 Java
14 python, java, java script, sql
15 NA
16 Java, SQL e python
17 Java,PHP
18 NA
19 Java
20 Python
21 C#, flutter, Dart, C, C++
22 Java, Flutter, SQL, Python
23 Phyton
24 Python, Rust
25 NA
26 C, Java, Python, SQL
27 Vibe coding
28 NA
29 NA
30 Python
31 Java, JavaScript, JSP em geral, HTML/CSS, Flutter/Dart. SQL em geral
32 Phyton, C, Java, Assembly
33 NA
34 NA
35 Python, HTML, JavaScript, CSS, SQL
36 NA
37 NA
38 Python
39 Python, SQL
40 Python
41 Javascript
42 Java
43 Java
44 Programação em c
45 C#
46 Java script, Java, Python, C#, Delphi
47 Java, SQL, HTML, CSS, JS
48 NA
49 Java
50 ABAP, SQL
51 Python, HTML e CSS
52 Python
53 Python
54 Python
55 C#; C++; Java; Python; html;
56 HTML, CSS, Javascript
   Você gosta de Matemática? Como você avalia seu conhecimento em Matemática? ⋯
1  Sim                       10                                               ⋯
2  Sim                        7                                               ⋯
3  Sim                        6                                               ⋯
4  Não                        6                                               ⋯
5  Sim                        7                                               ⋯
6  Sim                       10                                               ⋯
7  Sim                        7                                               ⋯
8  Sim                        6                                               ⋯
9  Sim                        7                                               ⋯
10 Sim                        8                                               ⋯
11 Sim                        5                                               ⋯
12 Sim                        7                                               ⋯
13 Sim                        6                                               ⋯
14 Sim                        7                                               ⋯
15 Sim                        6                                               ⋯
16 Sim                        7                                               ⋯
17 Sim                        6                                               ⋯
18 Sim                        6                                               ⋯
19 Sim                        5                                               ⋯
20 Sim                        7                                               ⋯
21 Sim                        6                                               ⋯
22 Não                        7                                               ⋯
23 Sim                        7                                               ⋯
24 Sim                        5                                               ⋯
25 Sim                        9                                               ⋯
26 Sim                        7                                               ⋯
27 Não                        3                                               ⋯
28 Sim                        8                                               ⋯
29 Sim                        7                                               ⋯
30 Sim                        6                                               ⋯
31 Não                        3                                               ⋯
32 Sim                        6                                               ⋯
33 Não                        8                                               ⋯
34 Sim                        5                                               ⋯
35 Sim                        8                                               ⋯
36 Sim                        7                                               ⋯
37 Sim                        7                                               ⋯
38 Sim                        6                                               ⋯
39 Sim                        8                                               ⋯
40 Sim                        7                                               ⋯
41 Sim                        5                                               ⋯
42 Sim                        7                                               ⋯
43 Não                        7                                               ⋯
44 Não                        7                                               ⋯
45 Não                        8                                               ⋯
46 Não                        6                                               ⋯
47 Sim                        5                                               ⋯
48 Sim                        8                                               ⋯
49 Sim                        8                                               ⋯
50 Sim                        8                                               ⋯
51 Não                        6                                               ⋯
52 Não                        6                                               ⋯
53 Não                        7                                               ⋯
54 Sim                        6                                               ⋯
55 Sim                        8                                               ⋯
56 Não                        5                                               ⋯
   Você trabalha atualmente?
1  Sim, período integral
2  Sim, período integral
3  Sim, período integral
4  Sim, período integral
5  Não
6  Sim, meio período
7  Sim, período integral
8  Sim, período integral
9  Sim, meio período
10 Sim, período integral
11 Sim, período integral
12 Não
13 Sim, período integral
14 Sim, meio período
15 Sim, período integral
16 Sim, período integral
17 Sim, período integral
18 Não
19 Sim, meio período
20 Não
21 Sim, período integral
22 Não
23 Sim, meio período
24 Sim, período integral
25 Não
26 Sim, período integral
27 Sim, período integral
28 Sim, período integral
29 Não
30 Sim, período integral
31 Sim, meio período
32 Não
33 Não
34 Sim, período integral
35 Não
36 Sim, período integral
37 Sim, período integral
38 Não
39 Sim, período integral
40 Sim, período integral
41 Sim, período integral
42 Sim, período integral
43 Sim, período integral
44 Sim, período integral
45 Sim, período integral
46 Sim, período integral
47 Sim, meio período
48 Não
49 Não
50 Sim, período integral
51 Não
52 Sim, meio período
53 Sim, meio período
54 Não
55 Sim, período integral
56 Sim, período integral
   Tempo diário médio de uso de redes sociais (em horas).
1  1 a 2
2  1 a 2
3  3 a 4
4  3 a 4
5  5 a 6
6  3 a 4
7  1 a 2
8  1 a 2
9  1 a 2
10 1 a 2
11 1 a 2
12 3 a 4
13 1 a 2
14 3 a 4
15 1 a 2
16 3 a 4
17 3 a 4
18 1 a 2
19 1 a 2
20 1 a 2
21 1 a 2
22 1 a 2
23 1 a 2
24 1 a 2
25 1 a 2
26 1 a 2
27 mais de 6
28 mais de 6
29 1 a 2
30 mais de 6
31 1 a 2
32 1 a 2
33 3 a 4
34 1 a 2
35 3 a 4
36 1 a 2
37 3 a 4
38 1 a 2
39 1 a 2
40 3 a 4
41 3 a 4
42 3 a 4
43 3 a 4
44 3 a 4
45 1 a 2
46 3 a 4
47 3 a 4
48 5 a 6
49 1 a 2
50 3 a 4
51 3 a 4
52 1 a 2
53 3 a 4
54 3 a 4
55 1 a 2
56 1 a 2
   Quantas vezes na semana, em média, você pratica atividade física?
1  2
2  1
3  3
4  2
5  2
6  2
7  2
8  0
9  3
10 0
11 3
12 2
13 1
14 5
15 4
16 2
17 5
18 0
19 7
20 4
21 4
22 5
23 mais que 7
24 2
25 4
26 2
27 5
28 mais que 7
29 4
30 3
31 2
32 3
33 5
34 3
35 5
36 5
37 3
38 1
39 0
40 1
41 0
42 1
43 5
44 4
45 4
46 2
47 4
48 4
49 0
50 1
51 2
52 5
53 3
54 4
55 0
56 3
   Como você avalia seu cuidado com sua alimentação? Quantos pets você tem?
1   6                                                2
2   4                                                0
3   4                                                2
4   5                                                2
5   2                                                2
6   5                                                0
7   5                                                1
8   7                                                2
9   8                                                2
10  7                                                3
11  7                                                0
12  5                                                mais que 10
13  5                                                4
14  7                                                3
15  4                                                0
16  8                                                0
17  8                                                2
18  8                                                4
19  8                                                0
20  8                                                1
21  5                                                0
22 10                                                5
23  8                                                1
24  8                                                0
25 10                                                1
26  7                                                1
27  8                                                2
28  8                                                1
29  5                                                mais que 10
30  7                                                3
31  4                                                5
32  6                                                3
33  9                                                0
34  7                                                0
35  6                                                1
36  8                                                1
37  8                                                2
38  3                                                2
39  8                                                4
40  5                                                1
41  5                                                0
42  3                                                2
43  7                                                2
44  7                                                4
45  7                                                1
46  8                                                3
47  6                                                1
48  2                                                1
49 10                                                2
50  5                                                1
51  6                                                0
52  8                                                1
53  7                                                1
54  7                                                0
55  9                                                0
56 10                                                1
   Quantos livros você leu no último ano? Quantos idiomas você fala?
1   7                                     1
2   1                                     1
3   0                                     2
4   0                                     1
5   8                                     2
6   0                                     2
7   2                                     1
8   3                                     2
9  35                                     2
10  0                                     1
11 23                                     2
12  0                                     2
13  2                                     2
14  0                                     2
15  1                                     1
16  5                                     1
17  3                                     1
18  1                                     1
19  1                                     1
20  5                                     2
21  5                                     2
22  3                                     3
23  5                                     3
24  2                                     3
25 12                                     2
26  4                                     1
27  0                                     3
28  1                                     1
29  2                                     1
30  2                                     2
31  2                                     2
32  4                                     2
33  5                                     3
34 23                                     2
35  5                                     2
36  0                                     1
37  9                                     3
38  2                                     2
39  7                                     2
40  1                                     1
41  0                                     0
42  1                                     3
43  1                                     1
44  1                                     1
45  0                                     2
46  2                                     2
47  4                                     2
48  0                                     2
49  0                                     1
50  1                                     2
51  2                                     2
52  3                                     2
53  0                                     1
54  3                                     3
55  3                                     1
56  2                                     2
   Você prefere:
1  Ambos
2  Trabalhar em equipe
3  Ambos
4  Ambos
5  Ambos
6  Ambos
7  Trabalhar em equipe
8  Ambos
9  Ambos
10 Ambos
11 Ambos
12 Ambos
13 Ambos
14 Ambos
15 Ambos
16 Ambos
17 Trabalhar individualmente
18 Ambos
19 Ambos
20 Ambos
21 Trabalhar individualmente
22 Trabalhar em equipe
23 Trabalhar em equipe
24 Ambos
25 Trabalhar em equipe
26 Trabalhar individualmente
27 Ambos
28 Ambos
29 Trabalhar em equipe
30 Ambos
31 Ambos
32 Ambos
33 Trabalhar em equipe
34 Ambos
35 Ambos
36 Trabalhar em equipe
37 Trabalhar individualmente
38 Trabalhar individualmente
39 Ambos
40 Trabalhar em equipe
41 Ambos
42 Ambos
43 Ambos
44 Ambos
45 Trabalhar em equipe
46 Ambos
47 Ambos
48 Ambos
49 Ambos
50 Trabalhar individualmente
51 Ambos
52 Ambos
53 Ambos
54 Ambos
55 Trabalhar em equipe
56 Ambos
   Principal motivo para escolher Ciência de Dados:
1  Oportunidades profissionais;Interesse em inovação;Transição de carreira;Interesse em tecnologia;
2  Interesse em tecnologia;Oportunidades profissionais;Interesse em inovação;
3  Oportunidades profissionais;Interesse em tecnologia;Transição de carreira;
4  Interesse em inovação;Interesse em tecnologia;Oportunidades profissionais;
5  Oportunidades profissionais;Interesse em tecnologia;Interesse em matemática/estatística;
6  Interesse em matemática/estatística;Interesse em tecnologia;Oportunidades profissionais;Interesse em inovação;Transição de carreira;
7  Oportunidades profissionais;Interesse em tecnologia;Interesse em inovação;Transição de carreira;
8  Interesse em tecnologia;Interesse em inovação;Transição de carreira;
9  Oportunidades profissionais;
10 Oportunidades profissionais;Interesse em tecnologia;Interesse em inovação;Interesse em matemática/estatística;Outros;
11 Interesse em inovação;Interesse em tecnologia;Outros;
12 Oportunidades profissionais;Interesse em tecnologia;
13 Interesse em tecnologia;Oportunidades profissionais;
14 Interesse em tecnologia;Interesse em inovação;Oportunidades profissionais;
15 Outros;
16 Oportunidades profissionais;Interesse em tecnologia;Interesse em inovação;
17 Oportunidades profissionais;Interesse em tecnologia;Interesse em inovação;Interesse em matemática/estatística;
18 Interesse em tecnologia;Interesse em inovação;Oportunidades profissionais;
19 Oportunidades profissionais;Interesse em inovação;Interesse em tecnologia;
20 Oportunidades profissionais;Interesse em tecnologia;Interesse em inovação;Interesse em matemática/estatística;
21 Oportunidades profissionais;Interesse em tecnologia;
22 Oportunidades profissionais;Interesse em tecnologia;Interesse em inovação;

In [ ]:
summary(df)

       ID          Semestre         Cidade de origem   Estado de origem
 Min.   : 1.00   Length:56          Length:56          Length:56
 1st Qu.:14.75   Class :character   Class :character   Class :character
 Median :28.50   Mode  :character   Mode  :character   Mode  :character
 Mean   :28.50
 3rd Qu.:42.25
 Max.   :56.00
 Cidade em que você reside atualmente.
 Length:56
 Class :character
 Mode  :character



 Você já morou em quantas cidades diferentes?
 Min.   :0.000
 1st Qu.:1.000
 Median :1.000
 Mean   :1.786
 3rd Qu.:2.000
 Max.   :9.000
 Você já teve contato com programação? Qual linguagem você já utilizou?
 Length:56                             Length:56
 Class :character                      Class :character
 Mode  :character                      Mode  :character



 Você gosta de Matemática? Como você avalia seu conhecimento em Matemática?
 Length:56                 Min.   : 3.000
 Class :character          1st Qu.: 6.000
 Mode  :character          Median : 7.000
                           Mean   : 6.661
                           3rd Qu.: 7.000
                           Max.   :10.000
 Data de nascimento:
 Min.   :1975-03-18 00:00:00
 1st Qu.:2003-02-24 18:00:00
 Median :2006-10-10 12:00:00
 Mean   :2004-07-01 10:17:08
 3rd Qu.:2008-01-01 18:00:00
 Max.   :2026-12-16 00:00:00
 Quantas horas (extra sala de aula) por semana você pretende se dedicar ao curso?
 Length:56
 Class :character
 Mode  :character



 Você trabalha atualmente?
 Length:56
 Class :character
 Mode  :character



 Tempo diário médio de uso de redes sociais (em horas).
 Length:56
 Class :character
 Mode  :character



 Quantas vezes na semana, em média, você pratica atividade física?
 Length:56
 Class :character
 Mode  :character



 Como você avalia seu cuidado com sua alimentação? Quantos pets você tem?
 Min.   : 2.000                                    Length:56
 1st Qu.: 5.000                                    Class :character
 Median : 7.000                                    Mode  :character
 Mean   : 6.571
 3rd Qu.: 8.000
 Max.   :10.000
 Quantos livros você leu no último ano? Quantos idiomas você fala?
 Min.   : 0.000                         Min.   :0.00
 1st Qu.: 1.000                         1st Qu.:1.00
 Median : 2.000                         Median :2.00
 Mean   : 3.821                         Mean   :1.75
 3rd Qu.: 4.250                         3rd Qu.:2.00
 Max.   :35.000                         Max.   :3.00
 Você prefere:      Principal motivo para escolher Ciência de Dados:
 Length:56          Length:56
 Class :character   Class :character
 Mode  :character   Mode  :character



 Áreas que mais te interessam:
 Length:56
 Class :character
 Mode  :character